### ISSUE TITLE
basicShorthandReplace not defined

### ISSUE THREAD

**Issue by ImanimalXI** [kevva/gulp-shorthand#1]
Hi! I get the error below when running the 1.1.0 version. The function call in margin-padding.js is not defined this part....

`else { // If all 4 margins are different
      // 4-value notation
      return basicShorthandReplace(shorthand, declarations);
  }`

ReferenceError: basicShorthandReplace is not defined
    at Object.module.exports [as getShorthandValue](DIR/node_modules/gulp-shorthand/node_modules/shrthnd/lib/shorthanders/margin-padding.js:19:14)
    at DIR/node_modules/gulp-shorthand/node_modules/shrthnd/lib/engine.js:20:40
    at Array.forEach (native)
    at DIR/node_modules/gulp-shorthand/node_modules/shrthnd/lib/engine.js:19:18
    at Array.forEach (native)
    at module.exports (DIR/node_modules/gulp-shorthand/node_modules/shrthnd/lib/engine.js:9:30)
    at DestroyableTransform._transform (DIR/node_modules/gulp-shorthand/index.js:20:14)
    at DestroyableTransform.Transform._read (DIR/node_modules/gulp-shorthand/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (DIR/node_modules/gulp-shorthand/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (DIR/node_modules/gulp-shorthand/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)

**Comment by kevva** [comment]
> Issues with the output should be reported on the shrthnd issue tracker.
